name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Vercel CLI
        run: nix-shell --command "bun i --global vercel@latest"

      - name: Pull Vercel Environment Information
        run: nix-shell --command "vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}"

      - name: Build Project Artifacts
        run: nix-shell --command "vercel build --token=${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy Project Artifacts to Vercel
        run: nix-shell --command "vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}"
